CREATE TABLE desktop_installation (
    id         INTEGER  PRIMARY KEY CHECK (id = 1),
    account_id INTEGER  NOT NULL UNIQUE REFERENCES accounts(id) ON DELETE RESTRICT,
    org_id     INTEGER  NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE RESTRICT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
