// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             int32              `json:"id"`
	Created        pgtype.Timestamptz `json:"created"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
}
