// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	UpdateUserHashedPassword(ctx context.Context, arg UpdateUserHashedPasswordParams) error
}

var _ Querier = (*Queries)(nil)
