// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetUser = `-- name: GetUser :one
SELECT id, created, email, hashed_password FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, GetUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created, email, hashed_password FROM users WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, GetUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const InsertUser = `-- name: InsertUser :one
INSERT INTO users (created, email, hashed_password)
VALUES ($1, $2, $3)
RETURNING id, created, email, hashed_password
`

type InsertUserParams struct {
	Created        pgtype.Timestamptz `json:"created"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, InsertUser, arg.Created, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Created,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const UpdateUserHashedPassword = `-- name: UpdateUserHashedPassword :exec
UPDATE users SET hashed_password = $1 WHERE id = $2
`

type UpdateUserHashedPasswordParams struct {
	HashedPassword string `json:"hashed_password"`
	ID             int32  `json:"id"`
}

func (q *Queries) UpdateUserHashedPassword(ctx context.Context, arg UpdateUserHashedPasswordParams) error {
	_, err := q.db.Exec(ctx, UpdateUserHashedPassword, arg.HashedPassword, arg.ID)
	return err
}
