{{- if .Values.secrets.create }}
{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sqlwarden.fullname" . }}
  labels:
    {{- include "sqlwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  cookie_secret_key: {{ .Values.secrets.cookieSecretKey | quote }}
  jwt_secret_key: {{ .Values.secrets.jwtSecretKey | quote }}
  encryption_key: {{ .Values.secrets.encryptionKey | quote }}
  connector_grant_signing_key: {{ .Values.secrets.connectorGrantSigningKey | quote }}
  {{- if not .Values.database.existingSecret }}
  {{ .Values.database.dsnKey }}: {{ .Values.database.dsn | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- if and (not .Values.database.existingSecret) (or (not .Values.secrets.create) .Values.secrets.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sqlwarden.databaseSecretName" . }}
  labels:
    {{- include "sqlwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.dsnKey }}: {{ .Values.database.dsn | quote }}
{{- end }}
