package oracle

import "strings"

// BuiltinFunction is shared by contextual completion and the editor's cached
// vocabulary. Names follow the Oracle 19c SQL function catalog:
// https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Functions.html
// Availability of individual functions still depends on the target version.
type BuiltinFunction struct {
	Name   string
	Detail string
}

var builtinFunctions = buildBuiltinFunctions()

func BuiltinFunctions() []BuiltinFunction {
	return append([]BuiltinFunction(nil), builtinFunctions...)
}

func buildBuiltinFunctions() []BuiltinFunction {
	groups := []struct{ category, names string }{
		{"numeric", `ABS ACOS ASIN ATAN ATAN2 BITAND CEIL COS COSH EXP FLOOR LN LOG MOD NANVL POWER REMAINDER ROUND SIGN SIN SINH SQRT TAN TANH TRUNC WIDTH_BUCKET`},
		{"character", `ASCII ASCIISTR CHR COMPOSE CONCAT DECOMPOSE INITCAP INSTR INSTRB INSTRC INSTR2 INSTR4 LENGTH LENGTHB LENGTHC LENGTH2 LENGTH4 LOWER LPAD LTRIM NCHR NLS_INITCAP NLS_LOWER NLS_UPPER NLSSORT REGEXP_COUNT REGEXP_INSTR REGEXP_REPLACE REGEXP_SUBSTR REPLACE RPAD RTRIM SOUNDEX SUBSTR SUBSTRB SUBSTRC SUBSTR2 SUBSTR4 TRANSLATE TRIM UNISTR UPPER`},
		{"datetime", `ADD_MONTHS CURRENT_DATE CURRENT_TIMESTAMP DBTIMEZONE EXTRACT FROM_TZ LAST_DAY LOCALTIMESTAMP MONTHS_BETWEEN NEW_TIME NEXT_DAY NUMTODSINTERVAL NUMTOYMINTERVAL SESSIONTIMEZONE SYS_EXTRACT_UTC SYSDATE SYSTIMESTAMP TO_DSINTERVAL TO_YMINTERVAL TZ_OFFSET`},
		{"conversion", `BIN_TO_NUM CAST CHARTOROWID CONVERT HEXTORAW RAWTOHEX RAWTONHEX ROWIDTOCHAR ROWIDTONCHAR SCN_TO_TIMESTAMP TIMESTAMP_TO_SCN TO_BINARY_DOUBLE TO_BINARY_FLOAT TO_BLOB TO_CHAR TO_CLOB TO_DATE TO_LOB TO_MULTI_BYTE TO_NCHAR TO_NCLOB TO_NUMBER TO_SINGLE_BYTE TO_TIMESTAMP TO_TIMESTAMP_TZ TO_UTC_TIMESTAMP_TZ VALIDATE_CONVERSION`},
		{"null and comparison", `COALESCE DECODE GREATEST LEAST LNNVL NULLIF NVL NVL2`},
		{"aggregate", `APPROX_COUNT_DISTINCT APPROX_MEDIAN APPROX_PERCENTILE AVG COLLECT CORR CORR_K CORR_S COUNT COVAR_POP COVAR_SAMP GROUPING GROUPING_ID LISTAGG MAX MEDIAN MIN REGR_AVGX REGR_AVGY REGR_COUNT REGR_INTERCEPT REGR_R2 REGR_SLOPE REGR_SXX REGR_SXY REGR_SYY STATS_BINOMIAL_TEST STATS_CROSSTAB STATS_F_TEST STATS_KS_TEST STATS_MODE STATS_MW_TEST STATS_ONE_WAY_ANOVA STATS_T_TEST_INDEP STATS_T_TEST_INDEPU STATS_T_TEST_ONE STATS_T_TEST_PAIRED STATS_WSR_TEST STDDEV STDDEV_POP STDDEV_SAMP SUM VAR_POP VAR_SAMP VARIANCE`},
		{"analytic", `CUME_DIST DENSE_RANK FIRST_VALUE LAG LAST_VALUE LEAD NTH_VALUE NTILE PERCENT_RANK PERCENTILE_CONT PERCENTILE_DISC RANK RATIO_TO_REPORT ROW_NUMBER`},
		{"JSON", `JSON_ARRAY JSON_ARRAYAGG JSON_DATAGUIDE JSON_MERGEPATCH JSON_OBJECT JSON_OBJECTAGG JSON_QUERY JSON_SERIALIZE JSON_VALUE`},
		{"XML", `EXISTSNODE EXTRACTVALUE XMLAGG XMLCAST XMLCDATA XMLCOLATTVAL XMLCOMMENT XMLCONCAT XMLDIFF XMLELEMENT XMLFOREST XMLISVALID XMLPARSE XMLPATCH XMLPI XMLQUERY XMLROOT XMLSEQUENCE XMLSERIALIZE XMLTRANSFORM`},
		{"LOB", `BFILENAME EMPTY_BLOB EMPTY_CLOB`},
		{"collection", `CARDINALITY`},
		{"environment and identifier", `DUMP ORA_HASH STANDARD_HASH SYS_CONTEXT SYS_GUID SYS_TYPEID UID USER USERENV VSIZE`},
		{"hierarchical", `SYS_CONNECT_BY_PATH`},
	}
	var result []BuiltinFunction
	for _, group := range groups {
		for _, name := range strings.Fields(group.names) {
			result = append(result, BuiltinFunction{Name: name, Detail: "Oracle " + group.category + " function"})
		}
	}
	return result
}
